namespace yyLib
{
    public static class yyGptImages
    {
        // https://platform.openai.com/docs/api-reference/images

        // The 'model' parameter specifies the image generation model to use.
        // It is an optional string that defaults to 'dall-e-2'.
        // Available options include 'dall-e-2' and 'dall-e-3'.
        // Choose the model based on your requirements for image quality and features.
        public static readonly string DefaultModel = "dall-e-3";

        // The 'quality' parameter determines the quality of the generated image when using the 'dall-e-3' model.
        // It is an optional string that defaults to 'standard'.
        // Valid values are:
        // - 'standard': Generates images quickly at a lower cost.
        // - 'hd': Produces images with finer details and greater consistency across the image, resulting in higher quality but also higher latency and cost.
        // Note: This parameter is only supported for 'dall-e-3' and has no effect when using 'dall-e-2'.
        public static readonly string DefaultQuality = "hd";

        // The 'size' parameter specifies the dimensions of the generated image.
        // It is an optional string that defaults to "1024x1024".
        // Accepted values vary based on the model:
        // - For 'dall-e-2': "256x256", "512x512", or "1024x1024".
        // - For 'dall-e-3': "1024x1024", "1792x1024", or "1024x1792".
        // Note: Specifying an unsupported size will result in an error.
        public static readonly string DefaultSize = "1024x1024";

        // The 'style' parameter defines the visual style of images generated by the 'dall-e-3' model.
        // It is an optional string that defaults to 'vivid'.
        // Accepted values are:
        // - 'vivid': Produces hyper-real and dramatic images.
        // - 'natural': Generates more natural, less hyper-realistic images.
        // Note: This parameter is only supported for 'dall-e-3' and has no effect when using 'dall-e-2'.
        public static readonly string DefaultStyle = "vivid";
    }
}
